{menu}
{START_FORM}
<p>{CONTACT_EMAIL_LABEL} {CONTACT_EMAIL}</p>
<p>{DUE_DATE_LABEL} {DUE_DATE}</p>
<p>{CC_ON_REFERENCE_EMAIL} {CC_ON_REFERENCE_EMAIL_LABEL}</p>
<p>{WKPDF_LABEL} {WKPDF}</p>
{SUBMIT}
{END_FORM}