CREATE TABLE IF NOT EXISTS douglas_applicants (
  id int NOT NULL,
  user_id int NOT NULL,
  stage smallint NOT NULL,
  last_name varchar(30) NOT NULL,
  first_name varchar(30) NOT NULL,
  created_date int NOT NULL,
  asu_box varchar(10) NOT NULL,
  banner_id varchar(15) NOT NULL,
  asu_username varchar(15) NOT NULL,
  phone varchar(15) NOT NULL,
  class_year varchar(10) NOT NULL,
  gpa varchar(5) NOT NULL,
  major varchar(20) NOT NULL,
  current_jobs text NOT NULL,
  professional_super varchar(50) NOT NULL,
  peer_super varchar(50) NOT NULL,
  employment_length varchar(50) NOT NULL,
  contributions text,
  organization1 varchar(40) DEFAULT NULL,
  organization2 varchar(40) DEFAULT NULL,
  organization3 varchar(40) DEFAULT NULL,
  office1 varchar(100) DEFAULT NULL,
  office2 varchar(100) DEFAULT NULL,
  office3 varchar(100) DEFAULT NULL,
  accomplish1 varchar(255) DEFAULT NULL,
  accomplish2 varchar(255) DEFAULT NULL,
  accomplish3 varchar(255) DEFAULT NULL,
  award1 varchar(40) DEFAULT NULL,
  award2 varchar(40) DEFAULT NULL,
  award3 varchar(40) DEFAULT NULL,
  received1 varchar(20) DEFAULT NULL,
  received2 varchar(20) DEFAULT NULL,
  received3 varchar(20) DEFAULT NULL,
  description1 text,
  description2 text,
  description3 text,
  reference_email1 varchar(40) DEFAULT NULL,
  reference_email2 varchar(40) DEFAULT NULL,
  reference_email3 varchar(40) DEFAULT NULL,
  reference1 varchar(100) DEFAULT NULL,
  reference2 varchar(100) DEFAULT NULL,
  reference3 varchar(100) DEFAULT NULL,
  resume varchar(150) DEFAULT NULL,
  essay varchar(150) DEFAULT NULL,
  completed smallint not null default 0,
  admin_comments text
  PRIMARY KEY (id)
);